# docker-compose.yml
services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/static:/var/www/static
    ports:
      - "80:80"
    depends_on:
      - app


  app:
    build: ./e-commerce
    volumes:
      - ./e-commerce:/e-commerce
    env_file:
      - .env-prod
    ports:
      - 8000:8000
    depends_on:
      - mongo
    command: gunicorn Ecommerce.wsgi:application --bind 0.0.0.0:8000
      
  mongo:
    image: mongo:6.0
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  